use_frameworks!

platform :ios, '9.0'

target 'SASwipeableButton_Example' do
  pod 'SASwipeableButton', :path => '../'

  target 'SASwipeableButton_Tests' do
    inherit! :search_paths

    
  end
end
